### ISSUE TITLE
[Server] As a developer, I should be able to turn on Stripe payments for customers to complete payment at checkout

### ISSUE THREAD

**Issue by luke-siedle** [gernzy/gernzy#94]
Using the new first/third party packaging system, we need to build a Stripe package that allows for checkout. Adding the required JavaScript to the jQuery client will be the easiest way to build this out I think. 

https://stripe.com/docs/js

1. At checkout, the user should see a credit card form, fill in their details. 
2. When submitting the form, Stripe creates a single use token for reusing that card information for the actual transaction. 
3. Transaction needs to be captured (possibly using the Stripe PHP sdk).

(Note that Stripe handles the secure passing of CC information and creates a single use secure token. We should never submit CC information to our own server/graphql). 

Stripe has a lot of features including webhooks which can send back updates on the payment flow, and this gets rather complicated to build into our current stack, but for now we just need the basics:

a) As a user, I can make a payment from a credit card form safely on checkout. 
b) As a user, after making payment I'm redirected to a confirmation page (we don't have this yet so can just say "Thank you" for now. 
c) As a tester, I should see an invoice come up from Stripe in my mailbox. 

For developers:
- Everything needs to be controlled from config. We should have a payments array in config that allows us to enable specific payment methods (Stripe being one of them).
- The Stripe package should have its own publishable config, with sane defaults.
- Because the Stripe package will be built in, we can include its dependencies in Gernzy. 

As you can tell, the more features/packages we add our config becomes more complex, so feel free to refactor things as required, even separating into separate files if needed. 

Might be good just to experiment with the Stripe libraries to begin with and understand the flow, and then start writing tests and adding features.

As usual TDD is really important since the payment flow can be quite complex at times, and there's both a front end and backend element to this.

**Comment by AlexeiaW** [comment]
TODO:
- [ ] https://stripe.com/docs/payments/accept-a-payment (tutorial)
- [ ] Try and moc https://api.stripe.com
- [ ] Still need to improve TDD test on backend and frontend
- [ ] How would a different payment provider integrate?
- [ ] Webhook needed for successful payment
- [ ] Handle curl errors
